module.exports = {
  DESCRIPTION: {
    0: 'zero',
    1: 'one',
    2: 'two',
    3: 'three',
    4: 'four',
    5: 'five',
    6: 'six',
    7: 'seven',
    8: 'eight',
    9: 'nine',
    10: 'ten',
    11: 'eleven',
    12: 'twelve',
    13: 'thirteen',
    14: 'fourteen',
    15: 'fifteen',
    16: 'sixteen',
    17: 'seventeen',
    18: 'eighteen',
    19: 'nineteen',
    20: 'twenty',
    30: 'thirty',
    40: 'fourty',
    50: 'fifty',
    60: 'sixty',
    70: 'seventy',
    80: 'eighty',
    90: 'ninety'
  },
  POWER_OF_10: ['', ' thousand', ' million', ' billion', ' trillion', ' quadrillion'],
  CURRENCY: {
    $: 'dollars'
  },
  GENERIC_ERROR: 'There was an unexpected error',
  INVALID_CURRENCY: 'Invalid currency',
  INVALID_AMOUNT: 'Invalid amount',
  NUMBER_OUT_OF_RANGE: 'number is not in a valid range'
};
